<?php include(PATH_CLASS.'crud'.SEP.'Funcoes.class.php');
$Funcoes = new Funcoes(DB_HOST, DB_USER, DB_PASS, DB_NAME);
$sistema = array(
    'titulo' => 'Banners',
    'titulo_cadastro' => 'Cadastro',
    'titulo_atualizar' => 'Atualizar',
    'titulo_atualizar_galeria' => 'Atualizar galeria',
    'bd' => $_SESSION['LANG'].'banners',
    'url' => 'banners',
    'order_by' => 'ABS(ordem)',
    'ordem' => 'ASC',
    'mostrar_excluir' => true, 
    'limitar' => true, 
    'quatidade_limite' => 5,
    'limitar_where' => '',
    'url_amigavel_por' => 'nome',
    'mostrar_clone' => false,
    'mostrar_alterar' => true,
    'mostar_voltar' => true,
    'mostar_incluir' => true,
    'list' => array(
        array(
            'nome' => 'Ordem',
            'bd' => 'ordem',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Imagem',
            'bd' => 'imagem',
            'type' => 'image',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Titulo',
            'bd' => 'nome',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Status',
            'bd' => 'status',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        )
    ),
    'search_custom' => false,
    'serch' => array( 'nome' ),
    'export_func' => false,
    'export' => array( array('Titulo' => 'nome'), array('Id' => 'id') ),
    'campos' => array(
        array(
            'name' => 'id',
            'type' => 'int',
            'amount' => '11',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'AUTO_INCREMENT',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'created',
            'type' => 'datetime',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'updated',
            'type' => 'datetime',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'url',
            'type' => 'varchar',
            'amount' => '100',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'ordem',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Ordem :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => false)
        ), array(
            'name' => 'nome',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Titulo :',
            'class_titulo' => 'col-xs-1 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => false, 'fechamento' => true)
        ), array(
            'name' => 'href',
            'type' => 'varchar',
            'amount' => 500,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Link :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => false)
        ), array(
            'name' => 'target',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Abrir em :',
            'class_titulo' => 'col-xs-1 align-r',
            'class' => 'col-xs-1',
            'input' => 'select',
            'category' => '',
            'parametros'=> array(
                array(
                    'conteudo' => array('_blank' => 'Nova aba', '_self' => 'Na mesma aba'),
                ),
            ),
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => false, 'fechamento' => true)
        ), array(
            'name' => 'imagem',
            'type' => 'varchar',
            'amount' => '200',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Imagem :<br><small class="red">(Tamanho 1920x700)</small>',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'image',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array( 'image' ),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'status',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Status :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        )
    ),
    'engine' => 'ENGINE=InnoDB',
    'primary' => 'id',
    'start_autoincrement' => 'AUTO_INCREMENT=1',
);

require(PATH_PAINEL.'_require.php'); ?>