<?php include(PATH_CLASS.'crud'.SEP.'Funcoes.class.php');
$Funcoes = new Funcoes(DB_HOST, DB_USER, DB_PASS, DB_NAME);
$sistema = array(
    'titulo' => 'Categorias',
    'titulo_cadastro' => 'Cadastro',
    'titulo_atualizar' => 'Atualizar',
    'titulo_atualizar_galeria' => 'Atualizar galeria',
    'bd' => $_SESSION['LANG'].'cadastrar_categoria',
    'url' => 'cadastrar-categoria',
    'order_by' => 'nome',
    'ordem' => 'ASC',
    'limitar' => false,
    'quatidade_limite' => 0,
    'mostrar_excluir' => true,
    'url_amigavel_por' => 'nome',
    'mostrar_clone' => false,
    'mostrar_alterar' => true,
    'mostar_voltar' => true,
    'mostar_incluir' => true,
    'list' => array(
        array(
            'nome' => 'Nome',
            'bd' => 'nome',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Status',
            'bd' => 'status',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        )
    ),
    'search_custom' => false,
    'serch' => array( 'nome' ),
    'export_func' => false,
    'export' => array( array('Nome' => 'nome'), array('Id' => 'id') ),
    'campos' => array(
        array(
            'name' => 'id',
            'type' => 'int',
            'amount' => '11',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'AUTO_INCREMENT',
            'mostrar_campo' => false,
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'created',
            'type' => 'datetime',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => '',
            'mostrar_campo' => false,
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'url',
            'type' => 'varchar',
            'amount' => '100',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'mostrar_campo' => false,
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'nome',
            'type' => 'varchar',
            'amount' => 200,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'mostrar_campo' => true,
            'titulo' => 'Nome :',
            'class_titulo' => 'col-xs-3 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'status',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'mostrar_campo' => true,
            'titulo' => 'Status :',
            'class_titulo' => 'col-xs-3 align-r',
            'class' => 'col-xs-6',
            'input' => 'checkbox',
            'category' => '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        )
    ),

    'engine' => 'ENGINE=InnoDB',
    'primary' => 'id',
    'start_autoincrement' => 'AUTO_INCREMENT=1',

);
require(PATH_PAINEL.'_require.php'); ?>