<?php include(PATH_CLASS.'crud'.SEP.'Funcoes.class.php');
$Funcoes = new Funcoes(DB_HOST, DB_USER, DB_PASS, DB_NAME);
$sistema = array(
    'titulo' => 'Notícias',
    'titulo_cadastro' => 'Cadastro',
    'titulo_atualizar' => 'Atualizar',
    'titulo_atualizar_galeria' => 'Atualizar galeria',
    'bd' => $_SESSION['LANG'].'noticias',
    'url' => 'noticias',
    'order_by' => 'ABS(ordem)',
    'ordem' => 'ASC',
    'mostrar_excluir' => true,
    'limitar' => false,
    'quatidade_limite' => 0,
    'limitar_where' => '',
    'enviar_dados_por_email' => '',
    'url_amigavel_por' => 'nome',
    'mostrar_clone' => false,
    'mostrar_alterar' =>  true,
    'mostar_voltar' => true,
    'mostar_incluir' => true,
    'list' => array(
        array(
            'nome' => 'Ordem',
            'bd' => 'ordem',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Categoria',
            'bd' => 'categoria',
            'type' => 'category',
            'category' => $_SESSION['LANG'].'cadastrar_categoria',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Nome',
            'bd' => 'nome',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Status',
            'bd' => 'status',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ),array(
            'nome' => 'Destaque Bloco 1|Home',
            'bd' => 'destaque',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Destaque Bloco 2|Home',
            'bd' => 'destaque_bloco_2',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        )
    ),
    'search_custom' => false,
    'serch' => array( 'nome' ),
    'export_func' => false,
    'export' => array( array('Nome' => 'nome'), array('Id' => 'id') ),
    'campos' => array(
        array(
            'name' => 'id',
            'type' => 'int',
            'amount' => '11',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'AUTO_INCREMENT',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'created',
            'type' => 'datetime',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'url',
            'type' => 'varchar',
            'amount' => '100',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'categoria',
            'type' => 'int',
            'amount' => 11,
            'colation' => '',
            'null' => '',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => true,
            'swap_reference' => '',
            'titulo' => 'Categoria :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'category',
            'category' => $_SESSION['LANG'].'cadastrar_categoria',
            'parametros'=> 'nome',
            'required' => true,
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ),  array(
            'name' => 'ordem',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Ordem :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'acessos',
            'type' => 'int',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => true,
            'swap_reference' => '',
            'titulo' => 'Acessos :',
            'class_titulo' => 'col-xs-1 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => false, 'fechamento' => true)
        ), array(
            'name' => 'nome',
            'type' => 'varchar',
            'amount' => 400,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Nome :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'data',
            'type' => 'date',
            'amount' => '',
            'colation' => '',
            'null' => '',
            'default' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Data :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-5',
            'input' => 'date',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'ano',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Ano da postagem da notícia :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'imagem',
            'type' => 'varchar',
            'amount' => '200',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Imagem :<br><small class="red">(Tamanho máximo 540x540)</small>',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'image',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('image'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'descritivo',
            'type' => 'text',
            'amount' => '',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => '',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Descritivo :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'textarea',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'descricao',
            'type' => 'text',
            'amount' => '',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => '',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Descrição :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-8',
            'input' => 'editor',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'status',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Status :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'destaque',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Destaque Bloco 1:',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'destaque_bloco_2',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Destaque Bloco 2:',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        )
    ),
    'engine' => 'ENGINE=InnoDB',
    'primary' => 'id',
    'start_autoincrement' => 'AUTO_INCREMENT=1',
);

require(PATH_PAINEL.'_require.php'); ?>