<?php include(PATH_CLASS.'crud'.SEP.'Funcoes.class.php');
$Funcoes = new Funcoes(DB_HOST, DB_USER, DB_PASS, DB_NAME);
$sistema = array(
    'titulo' => 'Produtos',
    'titulo_cadastro' => 'Cadastro',
    'titulo_atualizar' => 'Atualizar',
    'titulo_atualizar_galeria' => 'Atualizar galeria',
    'bd' => $_SESSION['LANG'].'produtos',
    'url' => 'produtos',
    'order_by' => 'nome',
    'ordem' => 'ASC',
    'mostrar_excluir' => true, 
    'limitar' => false, 
    'quatidade_limite' => 0,
    'limitar_where' => '',
    'url_amigavel_por' => 'nome',
    'mostrar_clone' => false,
    'mostrar_alterar' => true,
    'mostar_voltar' => true,
    'mostar_incluir' => true,
    'list' => array(
        array(
            'nome' => 'Nome',
            'bd' => 'nome',
            'type' => 'text',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Destaque',
            'bd' => 'destaque',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        ), array(
            'nome' => 'Status',
            'bd' => 'status',
            'type' => 'checkbox',
            'category' => '',
            'nivel_de_acesso' => array(1,2,3),
        )
    ),
    'search_custom' => false,
    'serch' => array( 'nome' ),
    'export_func' => false,
    'export' => array( array('Nome' => 'nome'), array('Id' => 'id') ),
    'campos' => array(
        array(
            'name' => 'id',
            'type' => 'int',
            'amount' => '11',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'AUTO_INCREMENT',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'created',
            'type' => 'datetime',
            'amount' => '',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'url',
            'type' => 'varchar',
            'amount' => '100',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => false,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => '',
            'class_titulo' => '',
            'class' => '',
            'input' => '',
            'category' => '',
            'parametros'=> '',
            'required' => '',
            'tipo_validacao' => '',
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'metadescription',
            'type' => 'text',
            'amount' => '',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => '',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Pequena descrição para o google :',
            'class_titulo' => 'col-xs-2 align-r',
            'class' => 'col-xs-4',
            'input' => 'textarea',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => false)
        ), array(
            'name' => 'keywords',
            'type' => 'text',
            'amount' => '',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => '',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Palavras chaves para a pesquisa do google :',
            'class_titulo' => 'col-xs-2 align-r',
            'class' => 'col-xs-4',
            'input' => 'textarea',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => false, 'fechamento' => true)
        ), array(
            'name' => 'nome',
            'type' => 'varchar',
            'amount' => 100,
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Nome :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-4',
            'input' => 'text',
            'category' => '',
            'parametros'=> '',
            'required' => true,
            'tipo_validacao' => array('vazio'),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'descricao',
            'type' => 'text',
            'amount' => '',
            'colation' => ' CHARACTER SET utf8 COLLATE utf8_general_ci',
            'null' => '',
            'default' => '',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Descrição :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-5',
            'input' => 'editor',
            'category' => '',
            'parametros' => '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'destaque',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Destaque :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        ), array(
            'name' => 'status',
            'type' => 'int',
            'amount' => '1',
            'colation' => '',
            'null' => 'NOT NULL',
            'default' => 'DEFAULT 0',
            'pre_select_logado' => '',
            'mostrar_campo' => true,
            'swap_change' => false,
            'swap_reference' => '',
            'titulo' => 'Status :',
            'class_titulo' => 'col-xs-4 align-r',
            'class' => 'col-xs-1',
            'input' => 'checkbox',
            'category' => '',
            'parametros'=> '',
            'required' => false,
            'tipo_validacao' => array(),
            'div' => array('abertura' => true, 'fechamento' => true)
        )
    ),
    'engine' => 'ENGINE=InnoDB',
    'primary' => 'id',
    'start_autoincrement' => 'AUTO_INCREMENT=1',
    'galeria' => array(
        array(
            'titulo' => 'Fotos',
            'bd' => $_SESSION['LANG'].'produtosfotos',
            'type' => 'images',
            'image_desta' => 'image',
            'legenda_desta' => 'legenda',
            'campos' => array(
                array(
                    'name' => 'id',
                    'type' => 'int',
                    'amount' => '11',
                    'colation' => '',
                    'null' => 'NOT NULL',
                    'default' => 'AUTO_INCREMENT',
                    'mostrar_campo' => false,
                    'titulo' => '',
                    'class' => '',
                    'input' => '',
                    'category' => '',
                    'parametros'=> '',
                    'required' => '',
                    'tipo_validacao' => ''
                ), array(
                    'name' => 'created',
                    'type' => 'date',
                    'amount' => '',
                    'colation' => '',
                    'null' => 'NOT NULL',
                    'default' => '',
                    'mostrar_campo' => false,
                    'titulo' => '',
                    'class' => '',
                    'input' => '',
                    'category' => '',
                    'parametros'=> '',
                    'required' => '',
                    'tipo_validacao' => ''
                ), array(
                    'name' => 'ordem',
                    'type' => 'int',
                    'amount' => '11',
                    'colation' => '',
                    'null' => 'NOT NULL',
                    'default' => 'DEFAULT 0',
                    'mostrar_campo' => false,
                    'titulo' => '',
                    'class' => '',
                    'input' => '',
                    'category' => '',
                    'parametros'=> '',
                    'required' => '',
                    'tipo_validacao' => ''
                ), array(
                    'name' => 'legenda',
                    'type' => 'varchar',
                    'amount' => 100,
                    'colation' => 'CHARACTER SET utf8 COLLATE utf8_general_ci',
                    'null' => 'NOT NULL',
                    'default' => 'DEFAULT 0',
                    'mostrar_campo' => true,
                    'titulo' => 'Legenda :',
                    'class' => 'col-xs-4',
                    'input' => 'text',
                    'category' => '',
                    'parametros'=> '',
                    'required' => false,
                    'tipo_validacao' => array()
                ), array(
                    'name' => 'image',
                    'type' => 'text',
                    'amount' => '',
                    'colation' => 'CHARACTER SET utf8 COLLATE utf8_general_ci',
                    'null' => '',
                    'default' => '',
                    'mostrar_campo' => true,
                    'titulo' => 'Imagem :<br><small class="red">(Tamanho maximo 1500x1500)</small>',
                    'class' => 'col-xs-5',
                    'input' => 'multi_image',
                    'parametros'=> '',
                    'required' => false,
                    'tipo_validacao' => array()
                ),
            ),

            'engine' => 'ENGINE=InnoDB',
            'primary' => 'id',
            'start_autoincrement' => 'AUTO_INCREMENT=1',
        ),

    ),
);

require(PATH_PAINEL.'_require.php'); ?>